name: ecommerce_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  persistent_bottom_nav_bar_v2: ^4.2.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
